baseurl: ""
styles: portfolio.min.css
print-styles: portfolio-print.min.css

url: "https://www.barrelofthis.com"
author: Matthew Dingee
repository: humancompanion/portfolio
github_url: https://github.com/humancompanion/portfolio

github: [metadata]

# Exclude from processing.
exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - css
  - compressing.sh
  - package-lock.json
